repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
        files: ^tests/other/.*\.py$
    -   id: trailing-whitespace
        files: ^tests/other/.*\.py$

-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
        args: ['--line-length', '99']
        language_version: python3
        additional_dependencies: ['click==8.0.4']
        files: ^tests/other/.*\.py$

-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest tests/other/
        language: system
        always_run: true
        pass_filenames: false
        working_dir: tests/other
        files: ^tests/other/
